const GET_DRIVERS = 'GET_DRIVERS'
const CLEAN_FILTERED_DRIVERS = 'CLEAN_FILTERED_DRIVERS'
const GET_DRIVER_BY_NAME = 'GET_DRIVER_BY_NAME'
const GET_TEAMS = 'GET_TEAMS'
const FILTER_BY_TEAMS = 'FILTER_BY_TEAMS'
const FILTER_BY_NATIONALITY = 'FILTER_BY_NATIONALITY'
const FILTER_BY_DB = 'FILTER_BY_DB'
const ORDER_BY_NAME = 'ORDER_BY_NAME'
const ORDER_BY_DOB = 'ORDER_BY_DOB'
const NEXT_PAGE = "NEXT_PAGE";
const PREV_PAGE = "PREV_PAGE";
const SPECIFIC_PAGE = "SPECIFIC_PAGE";
const SET_NOT_FOUND = "SET_NOT_FOUND";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_SEARCHED = "SET_SEARCHED"



export {
  GET_DRIVERS,
  CLEAN_FILTERED_DRIVERS,
  GET_DRIVER_BY_NAME,
  GET_TEAMS,
  FILTER_BY_TEAMS,
  FILTER_BY_NATIONALITY,
  FILTER_BY_DB,
  ORDER_BY_NAME,
  ORDER_BY_DOB,
  NEXT_PAGE,
  PREV_PAGE,
  SPECIFIC_PAGE,
  SET_NOT_FOUND,
  SET_CURRENT_PAGE,
  SET_SEARCHED
}